language: objective-c
osx_image: xcode11.2

branches:
  except:
    - localization
    - localization_1.1

env:
  global:
    - THEOS=theos

script:
- make package

before_install:
- gem install xcpretty
- brew install ldid fakeroot
- git clone --single-branch -b master https://github.com/theos/theos.git $THEOS
- cd $THEOS
- git config advice.detachedHead false
- git checkout 8771215
- git submodule update --init --recursive
- cd $TRAVIS_BUILD_DIR
