name: Build Zebra

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run: brew install ldid fakeroot

    - name: Setup Theos
      uses: actions/checkout@v2
      with:
        repository: theos/theos
        ref: 8771215f765e774bfefdacc6ddf0e151c2973d49
        path: theos
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: make package
