name: Upload Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      env:
        THEOS: theos
      run: |
        brew install ldid dpkg fakeroot
        git clone --depth=1 --recursive https://github.com/theos/theos.git $THEOS
        git submodule update --init --recursive

    - name: Build Package
      id: package_build
      env:
        THEOS: theos
      run: |
        make package FINALPACKAGE=1
        echo "::set-output name=package::$(ls -t packages | head -n1)"

    - name: Clone gh-pages
      run: |
        git clone -b gh-pages https://${{ github.repository_owner }}:${{ github.token }}@github.com/wstyres/Zebra.git ~/website
    - name: Move package to repo
      if: "!github.event.release.prerelease"
      run: |
        mkdir ~/website/repo/newpackages
        cd packages
        fn=$(ls -t | head -n1)
        echo $fn
        mv -f -- "$fn" ~/website/repo/newpackages
    - name: Move package to beta repo
      if: "github.event.release.prerelease"
      run: |
        mkdir ~/website/beta/newpackages
        cd packages
        fn=$(ls -t | head -n1)
        echo $fn
        mv -f -- "$fn" ~/website/beta/newpackages
    - name: Push repo
      if: "!github.event.release.prerelease"
      run: |
        cd ~/website
        chmod +x repo_update.sh
        ./repo_update.sh
    - name: Push beta repo
      if: "github.event.release.prerelease"
      run: |
        cd ~/website
        chmod +x beta_update.sh
        ./beta_update.sh

    - name: Attach package to release
      if: "!github.event.release.prerelease"
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: hub release edit -m '' -a ~/website/repo/pkgfiles/${{ steps.package_build.outputs.package }} '${{ github.event.release.tag_name }}'
    - name: Attach package to beta release
      if: github.event.release.prerelease
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: hub release edit -m '' -a ~/website/beta/pkgfiles/${{ steps.package_build.outputs.package }} '${{ github.event.release.tag_name }}'

    - name: Build IPA package
      id: ipa_build
      if: "!github.event.release.prerelease"
      env:
        THEOS: theos
      run: |
        make ipa
        echo "::set-output name=package::$(ls -t ipas | head -n1)"
    - name: Attach IPA to release
      if: "!github.event.release.prelease"
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: hub release edit -m '' -a ipas/${{ steps.ipa_build.outputs.package }} '${{ github.event.release.tag_name }}'
