name: Upload Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run: brew install ldid fakeroot dpkg

    - name: Setup Theos
      uses: actions/checkout@v2
      with:
        repository: theos/theos
        path: theos
        submodules: recursive

    - name: Build Package
      id: package_build
      env:
        THEOS: theos
      run: |
        make package FINALPACKAGE=1
        echo "::set-output name=package::$(ls -t packages | head -n1)"

    - name: Clone Safari
      run: git clone https://zbrabot:${{ secrets.BOT_TOKEN }}@github.com/zbrateam/Safari.git ~/website

    - name: Copy package to repo
      if: "!github.event.release.prerelease"
      working-directory: packages
      run: cp -f -- '${{ steps.package_build.outputs.package }}' ~/website/repo/pool

    - name: Copy package to beta repo
      if: "github.event.release.prerelease"
      working-directory: packages
      run: cp -f -- '${{ steps.package_build.outputs.package }}' ~/website/beta/pool

    - name: Push Safari
      working-directory: ~/website
      run: |
        git config --global user.name 'zbrabot'
        git config --global user.email 'zbrabot@users.noreply.github.com'
        git add .
        git commit -m '${{ github.event.release.tag_name }}'
        git push

    - name: Attach package to release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      working-directory: packages
      run: gh release upload '${{ github.event.release.tag_name }}' '${{ steps.package_build.outputs.package }}'
